### ISSUE TITLE
Requires unreleased versions of versa and amara3-iri

### ISSUE THREAD

**Issue by osma** [zepheira/pybibframe#12]
I'm trying to install pybibframe according to the instructions in README.md. However, the command `pip install -r requirements.txt` installs versions of versa and amara3-iri that don't actually work with current pybibframe:

```
$ ~/sw/pybibframe-venv/bin/marc2bf 
Traceback (most recent call last):
  File "/home/oisuomin/sw/pybibframe-venv/bin/marc2bf", line 79, in <module>
    run(inputs=args.inputs, base=args.base, out=args.out, limit=args.limit, rdfttl=args.rdfttl, rdfxml=args.rdfxml, xml=args.xml, config=args.config, verbose=args.verbose, mods=args.mod, canonical=args.canonical, lax=args.lax)
  File "/home/oisuomin/sw/pybibframe-venv/bin/marc2bf", line 32, in run
    lax=lax, defaultsourcetype=inputsourcetype.filename)
  File "/home/oisuomin/sw/pybibframe-venv/lib/python3.4/site-packages/bibframe/reader/engine.py", line 109, in bfconvert
    inputs = factory(inputs, defaultsourcetype=defaultsourcetype, streamopenmode=readmode)
TypeError: factory() got an unexpected keyword argument 'defaultsourcetype'
```

I eventually got pybibframe working by manually removing the pip-installed `amara3*` and `versa` modules from site-packages (I'm using a virtual environment built with Python 3.4 `venv`, as you can probably guess from the above traceback), cloned versa, amara3-iri and amara3-xml from GitHub and installed each of them using `setup.py`.

It appears that the API of these modules has changed since their latest PyPI releases and pybibframe relies on the new API, but specifies dependencies on the older versions available on PyPI. To fix this, new versions of these modules should be released on PyPI (probably by @uogbuji ?) and then requirements.txt should be updated to require the new versions.

**Comment by distobj** [comment]
Thanks so much for the prod! New versions of versa and amara3-iri were just released, and pybibframe's dependencies updated. Please confirm that it works for you, and close the issue if it does.

Thanks again.

**Comment by osma** [comment]
Thanks a lot, it works now and installing is now much easier! Closing issue.
