### ISSUE TITLE
marc2bf 'Requirement to convert link target to IRI failed for invalid input'

### ISSUE THREAD

**Issue by remerjohnson** [zepheira/pybibframe#13]
When I try to run marc2f to convert a record, I get tons of WARNING messages, for example: 

`WARNING:marc2bf:Requirement to convert link target to IRI failed for invalid input, causing the corresponding output link to be omitted entirely: (I(hpp6TLv1L24), I(http://bibfra.me/vocab/lite/link), 'http://www.degruyter.com/isbn/9781501502170    ')`

After keyboard interrupt, the only clues I can see seem to be around a module, but which the only solutions I've seen involve reinstalling Python: 

`FileNotFoundError: [Errno 2] No such file or directory: '-------src-dir-------/Python-3.5.1/Modules/pyexpat.c'`

**Comment by distobj** [comment]
Hi. That's a common warning as we currently make no attempt to sanitize or encode the field, and is not indicative of any issue with your environment. In this case, what's supposed to be a URI ends in a space and so cannot be turned into an IRI. We get lots of those warnings too as you might imagine, and haven't spent much time thinking about how to clean this up, other than to observe (as your example demonstrates) that actions such as percent-encoding wouldn't necessarily always be appropriate.
