### ISSUE TITLE
Sustainable IRIs

### ISSUE THREAD

**Issue by pheyvaer** [zepheira/pybibframe#20]
I tried creating RDF from this example `https://lccn.loc.gov/2006013175/marcxml`, but I see that for the subjects random identifiers are used. How is this sustainable if you regenerate your RDF at a later stage?

**Comment by distobj** [comment]
Hi Pieter. All identifiers are deterministic, based on a hash of the fields specified in the unique() clause of the relevant rule from lib/reader/marcpatterns.py. As long as those consulted field values stay the same between runs, then the identifier will too.

**Comment by pheyvaer** [comment]
OK, and how difficult is it to, for example, do something custom with the IRI? Let's say that instead of the hash value I want `http://www.example.org/{HASH}`, where `{HASH}` is the hash value of every entity.

**Comment by distobj** [comment]
If you mean setting a base URI, there's a command line feature for that, --base

**Comment by pheyvaer** [comment]
Ok, thanks for the explanation :)

**Comment by uogbuji** [comment]
For some reason I wasn't getting all e-mail notifications for this thread. Just for completeness, see [details of the hash algorithm](https://github.com/zepheira/pybibframe/wiki/From-Records-to-Resources:-the-Library.Link-resource-ID-generation-algorithm).
