### ISSUE TITLE
parse_versa requires amara3 (reported by https://github.com/azaroth42)

### ISSUE THREAD

**Issue by uogbuji** [zepheira/pybibframe#6]
```
Traceback (most recent call last):
  File "/Users/azaroth/install/bin/parse_versa", line 24, in <module>
    from versa.reader.md import from_markdown
  File "/Users/azaroth/install/lib/python3.4/site-packages/versa/reader/md.py", line 18, in <module>
    from amara3.uxml.parser import parse, event
ImportError: No module named 'amara3.uxml'
```

pip3 install amara gets amara-2.0.0 which doesn't install.
pip3 install amara3 doesn't find anything.

Giving up.

**Comment by jadeeshah** [comment]
I am having the same issue and PyPI does not have the latest 0.4.1 version.

**Comment by uogbuji** [comment]
@jadeeshah very sorry for the delay in getting to this. I knew a new release was due anyway, and I finally squeezed out 0.5.0 and all its dependencies.

I have confirmed that a simple `pip install pybibframe` (with or without `-U`). You no longer need to mess with `requirements.txt`. If you continue to have trouble let me know. Thanks.
