### ISSUE TITLE
FROM_EMPTY_HASH-> FROM_EMPTY_64BIT_HASH

### ISSUE THREAD

**Issue by dfeeney** [zepheira/pybibframe#9]
It looks like FROM_EMPTY_HASH in [lib/reader/marc.py](https://github.com/zepheira/pybibframe/blob/master/lib/reader/marc.py ) should be changed to FROM_EMPTY_64BIT_HASH.

**Comment by uogbuji** [comment]
Correct. Hmm. Looks as if I'd only checked in half of that update. Fixed.
